import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const workspace = resolve(root, "../..");
const source = await readFile(resolve(root, "src/code.js"), "utf8");
const ui = await readFile(resolve(root, "src/ui.html"), "utf8");

const brand = await readFile(
  resolve(workspace, "docs/design/assets/characters/dodami-brand-yellow-scarf.png"),
);
const drawing = await readFile(
  resolve(workspace, "docs/design/assets/characters/dodami-drawing-yellow-scarf.png"),
);

const banner = [
  "/*",
  " * Generated by tools/figma-dodam-child/build.mjs.",
  " * Edit src/code.js instead of dist/code.js.",
  " */",
  `const DODAMI_BRAND_BASE64 = "${brand.toString("base64")}";`,
  `const DODAMI_DRAWING_BASE64 = "${drawing.toString("base64")}";`,
  "",
].join("\n");

await mkdir(resolve(root, "dist"), { recursive: true });
await writeFile(resolve(root, "dist/code.js"), banner + source, "utf8");
await writeFile(resolve(root, "dist/ui.html"), ui, "utf8");

console.log("Built Dodam Child UI Generator");
console.log(`- dist/code.js (${(banner.length + source.length).toLocaleString()} chars)`);
console.log(`- dist/ui.html (${ui.length.toLocaleString()} chars)`);
